backend:
  name: github
  repo: abogutalan/i3-website
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/myAssets/img
public_folder: /myAssets/img

collections:
  
  - name: instructors
    label: Instructors
    folder: src/pages/YD/YDInstructors
    slug: "{{name}}-{{templateKey}}"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "instructorTemplate"}
      - { name: name, label: Instructor Name, widget: string }
      - { name: imgURL, label: Featured Image, widget: image }
      - { name: "description", label: "Description", widget: "text"}
      - { name: "descriptionMore", label: "More Description", widget: "text", required: false}

  - name: locations
    label: Locations
    folder: src/pages/YD/YDLocations
    slug: "{{name}}-{{templateKey}}"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "locationTemplate"}
      - { name: address, label: Address, widget: string }
      - { name: featuredimage, label: Featured Image, widget: image }
      - { name: name, label: Instructor Name, widget: string }
      - { name: "timing", label: "Timing", widget: "text"}

  - name: fellow
    label: Fellows
    folder: src/pages/research/Fellows
    slug: "{{name}}-{{templateKey}}"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "fellowTemplate"}
      - { name: name, label: Fellow Name, widget: string }
      - { name: title, label: Title }
      - { name: "description", label: "Description", widget: "text"}
      - { name: imgURL, label: Image, widget: image }
      - { name: facebook_url, label: Facebook URL, widget: string, default: "", required: false }
      - { name: twitter_url, label: Twitter URL, widget: string, default: "", required: false }
      - { name: instagram_url, label: Instagram URL, widget: string, default: "", required: false }
      - { name: youtube_url, label: Youtube URL, widget: string, default: "", required: false }
      - { name: google_url, label: Google+ URL, widget: string, default: "", required: false }
      - { name: linkedin_url, label: LinkedIn URL, widget: string, default: "", required: false }
    
  - name: event
    label: Events
    folder: src/pages/programs/Events
    slug: "{{name}}-{{templateKey}}"
    create: true
    fields:
      - { name: imgURL, label: Image, widget: image }
      - { name: name, label: Event Name, widget: string }
      - { name: location, label: Location, widget: "text" }
      - { name: DT, label: Date/Time, widget: "text"}
      - { name: "description", label: "Description", widget: "text"}
      - { name: isCurrentEvent, label: Is it a current event?, widget: boolean, default: false, required: false }
      
      
      
