backend:
  name: github
  repo: abogutalan/i3-website
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/myAssets/img
public_folder: static/myAssets/img

collections:
  - name: blog
    label: Blog
    folder: src/pages/markdown-pages
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blogTemplate"}
      - { name: slug, label: Slug }
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - {label: "Tags", name: "tags", widget: "list"}
  
  - name: instructors
    label: Instructors
    folder: src/pages/YD/YDInstructors
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "instructorTemplate"}
      - { name: name, label: Instructor Name, widget: string }
      - { name: imgURL, label: Featured Image, widget: image }
      - { name: "description", label: "Description", widget: "text"}
      - { name: "descriptionMore", label: "More Description", widget: "text", required: false}
      - { name: slug, label: Slug, widget: "hidden", default: "/YD/YDInstructors/YDInstructors" }

  - name: locations
    label: Locations
    folder: src/location
    create: true
    fields:
      - { name: adress, label: Adress, widget: string }
      - { name: featuredimage, label: Featured Image, widget: image }
      - { name: instructorname, label: Instructor Name, widget: string }
      - { name: "timing", label: "Timing", widget: "text"}

  - name: fellow
    label: Fellows
    folder: src/fellow
    create: true
    fields:
      - { name: fellowname, label: Fellow Name, widget: string }
      - { name: title, label: Title }
      - { name: "newdescription", label: "Description", widget: "text"}
      - { name: url, label: URL, widget: string }
    
    

      
