backend:
  name: github
  repo: abogutalan/i3-website
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/myAssets/img
public_folder: myAssets/img

collections:
  
  - name: instructors
    label: Instructors
    folder: src/pages/YD/YDInstructors
    slug: "{{name}}-{{templateKey}}"
    media_folder: "/static/myAssets/img/instructors"
    public_folder: "/static/myAssets/img/instructors"
    create: true
    fields:
      - {label: Template Key, name: templateKey, widget: hidden, default: instructorTemplate }
      - { name: name, label: Instructor Name, widget: string }
      - { name: imgURL, label: Featured Image, widget: image }
      - { name: description, label: Description, widget: text }
      - { name: descriptionMore, label: More Description, widget: text, required: false }
      - { name: rank, label: Rank, widget: number, valueType: int }

  - name: locations
    label: Locations
    folder: src/pages/YD/YDLocations
    slug: "{{address}}-{{templateKey}}"
    media_folder: "/static/myAssets/img/Locations"
    public_folder: "/static/myAssets/img/Locations"
    create: true
    fields:
      - {label: Template Key, name: templateKey, widget: hidden, default: locationTemplate }
      - { name: name, label: Address, widget: string }
      - { name: featuredimage, label: Featured Image, widget: image }
      - { name: instructor, label: Instructor Name, widget: string }
      - { name: timing, label: Timing, widget: text}

  - name: fellow
    label: Fellows
    folder: src/pages/research/Fellows
    slug: "{{name}}-{{templateKey}}"
    media_folder: "/static/myAssets/img/Research Center/Fellows"
    public_folder: "/static/myAssets/img/Research Center/Fellows"
    create: true
    fields:
      - {label: Template Key, name: templateKey, widget: hidden, default: fellowTemplate }
      - {label: Slug, name: slug, widget: hidden, default: /research/fellows/ }
      - { name: name, label: Fellow Name, widget: string }
      - { name: title, label: Title }
      - { name: description, label: Description, widget: text }
      - { name: body, label: More Description, widget: markdown }
      - { name: imgURL, label: Image, widget: image }
      - { name: facebook_url, label: Facebook URL, widget: string, default: "", required: false }
      - { name: twitter_url, label: Twitter URL, widget: string, default: "", required: false }
      - { name: instagram_url, label: Instagram URL, widget: string, default: "", required: false }
      - { name: youtube_url, label: Youtube URL, widget: string, default: "", required: false }
      - { name: google_url, label: Google+ URL, widget: string, default: "", required: false }
      - { name: linkedin_url, label: LinkedIn URL, widget: string, default: "", required: false }
      - { name: rank, label: Rank, widget: number, valueType: int }
    
  - name: event
    label: Events
    folder: src/pages/programs/Events
    slug: "{{name}}-{{templateKey}}"
    media_folder: "/static/myAssets/img/events"
    public_folder: "/static/myAssets/img/events"
    create: true
    fields:
      - {label: Template Key, name: templateKey, widget: hidden, default: eventTemplate}
      - { name: imgURL, label: Image, widget: image }
      - { name: name, label: Event Name, widget: string }
      - { name: location, label: Location, widget: text }
      - { name: DT, label: Date/Time, widget: text }
      - { name: description, label: Description, widget: text }
      - { name: isCurrentEvent, label: Is it a current event?, widget: boolean, default: false, required: false }

  - name: counselors
    label: Counselors
    folder: src/pages/programs/FCC/FCCCounselors
    slug: "{{name}}-{{templateKey}}"
    media_folder: "/static/myAssets/img/FaithCrisis"
    public_folder: "/static/myAssets/img/FaithCrisis"
    create: true
    fields:
      - {label: Template Key, name: templateKey, widget: hidden, default: counselorTemplate }
      - { name: name, label: Counselor Name, widget: string }
      - { name: title, label: Position, widget: string }
      - { name: imgURL, label: Featured Image, widget: image }
      - { name: education, label: Education, widget: text }
      - { name: otherInterests, label: Hobbies, widget: text }
      - { name: link, label: Link/e-mail, widget: string }
      - { name: linkDisplay, label: link (on screen), widget: string }
      - { name: instructions, label: Special Instructions, widget: string, required: false }
      - { name: booklink, label: Link to booking page, widget: string }
      - { name: gender, label: Gender, widget: string }
      - { name: rank, label: Rank, widget: number, valueType: int }

  - name: volunteers
    label: Volunteer Positions
    folder: src/pages/about/Volunteer/VolunteerPositions
    slug: "{{jobTitle}}-{{templateKey}}"
    create: true
    fields:
      - {label: Template Key, name: templateKey, widget: hidden, default: volunteerTemplate }
      - { name: jobTitle, label: Position, widget: string, default: "Enter Position Here" }
      - { name: jobTeam, label: Department, widget: string, default: "Enter Department Here" }
      - { name: description, label: Job Description, widget: text}
      - { name: duties, label: Duties and Responsibilities, widget: markdown }
      - { name: qualifications, label: Qualifications, widget: markdown }

  - name: slider
    label: Slider Testimonials
    folder: src/pages/about/testimonials/sliders
    slug: "{{author}}-{{templateKey}}"
    media_folder: "/static/myAssets/img/testimonials"
    public_folder: "/myAssets/img/testimonials"
    create: true
    fields:
      - {label: Template Key, name: templateKey, widget: hidden, default: carouselTemplate }
      - { name: imgSlider, label: Image, widget: image }
      - { name: quote, label: Quote, widget: text}
      - { name: author, label: Author, widget: string }
      - { name: position, label: Position, widget: string }
      
      
      
      
